"""Self-contained HTML workbench for non-technical review and approval."""
from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any, Mapping


def _json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False).replace("</", "<\\/")


def generate_html_report(report: Mapping[str, Any], *, output_dir: str | Path, title: str = "Web UI Quality Review") -> Path:
    out = Path(output_dir); out.mkdir(parents=True, exist_ok=True)
    data_path = out / "report-data.json"
    data_path.write_text(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")
    browser = report.get("browserComparisonReport", {}) if isinstance(report, Mapping) else {}
    before_ref = browser.get("beforeRef") if isinstance(browser, Mapping) else None
    after_ref = browser.get("afterRef") if isinstance(browser, Mapping) else None
    browser_dir = str(browser.get("outputDirectory") or "browser") if isinstance(browser, Mapping) else "browser"
    before_ref = f"../{browser_dir}/{before_ref}" if before_ref and before_ref != "NOT_VERIFIED" else ""
    after_ref = f"../{browser_dir}/{after_ref}" if after_ref and after_ref != "NOT_VERIFIED" else ""
    payload = _json(report)
    page = f'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title><style>
:root{{--bg:#f4f6f8;--surface:#fff;--text:#17202a;--muted:#637083;--line:#dce2e8;--brand:#1769e0;--good:#087f5b;--warn:#a85d00;--bad:#c92a2a}}
*{{box-sizing:border-box}}body{{margin:0;font:14px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}}
header{{position:sticky;top:0;z-index:5;background:#111827;color:#fff;padding:16px 24px;display:flex;justify-content:space-between;align-items:center}}h1{{font-size:20px;margin:0}}button,.btn{{border:1px solid var(--line);background:#fff;border-radius:8px;padding:8px 12px;cursor:pointer}}header button{{background:#24324a;color:#fff;border-color:#3a4962}}main{{max-width:1440px;margin:auto;padding:20px}}.scoregrid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}}.card{{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:16px;box-shadow:0 1px 2px #0000000a}}.score{{font-size:28px;font-weight:750}}.muted{{color:var(--muted)}}.tabs{{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}}.tab.active{{background:var(--brand);color:#fff;border-color:var(--brand)}}section[data-panel]{{display:none}}section[data-panel].active{{display:block}}table{{width:100%;border-collapse:collapse}}th,td{{padding:10px;border-bottom:1px solid var(--line);vertical-align:top;text-align:left}}.P0,.P1,.FAIL{{color:var(--bad);font-weight:700}}.P2,.PASS_WITH_WARNINGS{{color:var(--warn);font-weight:700}}.PASS{{color:var(--good);font-weight:700}}pre{{white-space:pre-wrap;word-break:break-word;background:#111827;color:#e5e7eb;padding:14px;border-radius:8px;max-height:520px;overflow:auto}}.compare{{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:10px;background:#ddd;min-height:260px}}.compare img{{width:100%;display:block}}.compare .after{{position:absolute;inset:0;clip-path:inset(0 50% 0 0)}}.compare input{{position:absolute;left:10%;right:10%;bottom:12px;width:80%;z-index:3}}textarea,select,input[type=text]{{width:100%;padding:9px;border:1px solid var(--line);border-radius:7px}}.review{{display:grid;grid-template-columns:180px 1fr;gap:12px}}.pill{{display:inline-block;padding:3px 8px;border-radius:999px;background:#eef2f7;margin:2px}}@media(max-width:720px){{main{{padding:12px}}.review{{grid-template-columns:1fr}}header{{align-items:flex-start;gap:10px;flex-direction:column}}}}
</style></head><body><header><div><h1>{html.escape(title)}</h1><div id="headline"></div></div><div><button onclick="exportReview()">导出评审记录</button></div></header><main>
<div id="scores" class="scoregrid"></div><div class="tabs" id="tabs"></div>
<section data-panel="summary" class="active"><div class="card"><h2>推荐方案</h2><div id="recommendation"></div></div><div class="card" style="margin-top:12px"><h2>视觉改善判断</h2><div id="visualJudgment"></div></div><div class="card" style="margin-top:12px"><h2>未验证与风险</h2><div id="risks"></div></div></section>
<section data-panel="experience"><div class="card"><h2>体验方案</h2><div id="experiencePlan"></div></div><div class="card" style="margin-top:12px"><h2>交互与状态</h2><div id="interactionPlan"></div></div></section>
<section data-panel="compare"><div class="card"><h2>Before / After</h2><div class="compare" id="compareBox"><img src="{html.escape(str(before_ref or ''))}" alt="Before"><img class="after" src="{html.escape(str(after_ref or ''))}" alt="After"><input aria-label="对比滑块" type="range" min="0" max="100" value="50"></div><p class="muted">滑动查看同条件截图。截图不存在时请检查 Browser 运行状态。</p></div></section>
<section data-panel="findings"><div class="card"><h2>问题清单</h2><table><thead><tr><th>等级</th><th>ID</th><th>问题</th><th>证据/建议</th></tr></thead><tbody id="findingRows"></tbody></table></div></section>
<section data-panel="journey"><div class="card"><h2>关键旅程</h2><table><thead><tr><th>状态</th><th>步骤</th><th>耗时</th><th>说明</th></tr></thead><tbody id="journeyRows"></tbody></table></div></section>
<section data-panel="engines"><div class="card"><h2>专业引擎</h2><div id="engines"></div></div></section>
<section data-panel="review"><div class="card"><h2>评审与协作</h2><div class="review"><label>结论</label><select id="decision"><option>NOT_REVIEWED</option><option>APPROVED</option><option>CHANGES_REQUESTED</option><option>REJECTED</option></select><label>评审人</label><input id="reviewer" type="text"><label>评论</label><textarea id="comment" rows="8"></textarea></div><p><button onclick="saveReview()">保存到本机</button></p><h3>历史</h3><div id="history"></div></div></section>
<section data-panel="raw"><div class="card"><h2>原始结构化报告</h2><pre id="raw"></pre></div></section>
</main><script>
const REPORT={payload}; const KEY='wuq-review:'+((REPORT.reportDigest||REPORT.planDigest||location.pathname));
const scorecard=REPORT.scorecard||{{}}; document.getElementById('headline').textContent=(REPORT.overallResult||REPORT.verificationReport?.result||'NOT_VERIFIED')+' · '+(REPORT.maturity||REPORT.uiProductCapability?.evidenceAndDelivery?.maturity||'unknown');
const labels={{productDecision:'产品方向',browser:'Browser',journey:'关键旅程',renderedQuality:'渲染质量',professionalEngines:'专业引擎',overall:'综合'}};
document.getElementById('scores').innerHTML=Object.entries(scorecard).map(([k,v])=>`<div class="card"><div class="muted">${{labels[k]||k}}</div><div class="score">${{typeof v==='object'?(v.score??'-'):v}}</div><div class="muted">${{typeof v==='object'?(v.status||''):''}}</div></div>`).join('');
const tabs=[['summary','总览'],['experience','体验方案'],['compare','前后对比'],['findings','问题'],['journey','旅程'],['engines','专业引擎'],['review','评审'],['raw','原始报告']];document.getElementById('tabs').innerHTML=tabs.map((t,i)=>`<button class="tab ${{i?'':'active'}}" data-tab="${{t[0]}}">${{t[1]}}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{{document.querySelectorAll('.tab,section[data-panel]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(`[data-panel="${{b.dataset.tab}}"]`).classList.add('active')}});
const plan=REPORT.productizationPlan||{{}};const cap=REPORT.uiProductCapability||{{}};document.getElementById('recommendation').innerHTML=`<h3>${{escapeHtml(plan.recommendation||cap.selectedDirection?.name||'未生成')}}</h3><p>${{escapeHtml(plan.selectionReason||cap.selectedDirection?.reason||'')}}</p><div>${{(plan.keyTradeoffs||[]).map(x=>`<span class=pill>${{escapeHtml(x)}}</span>`).join('')}}</div>`;
const experience=REPORT.experienceCore||{{}};const selected=experience.selectedPattern||{{}};const visual=experience.visualSystem||{{}};document.getElementById('experiencePlan').innerHTML=`<h3>${{escapeHtml(selected.name||'未生成')}}</h3><p>${{escapeHtml(selected.summary||'')}}</p><p><b>视觉方向：</b>${{escapeHtml(visual.directionName||'未生成')}} · <b>密度：</b>${{escapeHtml(visual.density||'')}}</p><p><b>桌面：</b>${{escapeHtml(selected.composition?.desktop||'')}}</p><p><b>中间：</b>${{escapeHtml(selected.composition?.tablet||'')}}</p><p><b>移动：</b>${{escapeHtml(selected.composition?.mobile||'')}}</p><div>${{(selected.modernFeatures||[]).map(x=>`<span class=pill>${{escapeHtml(x)}}</span>`).join('')}}</div>`;const interaction=experience.interactionContract||{{}};document.getElementById('interactionPlan').innerHTML=`<p><b>主任务：</b>${{escapeHtml(interaction.primaryTask||'')}}</p><p>${{(interaction.primaryInteractions||[]).map(x=>`<span class=pill>${{escapeHtml(x)}}</span>`).join('')}}</p><table><thead><tr><th>状态</th><th>呈现</th><th>恢复</th></tr></thead><tbody>${{(interaction.stateCoverage||[]).map(x=>`<tr><td>${{escapeHtml(x.id)}}</td><td>${{escapeHtml(x.presentation)}}</td><td>${{escapeHtml(x.action)}}</td></tr>`).join('')}}</tbody></table>`;
const vj=REPORT.visualJudgment||REPORT.professionalEngines?.visualJudgment||{{status:'INCONCLUSIVE',confidence:'low',reasons:['尚未生成视觉改善判断。']}};document.getElementById('visualJudgment').innerHTML=`<p><b>${{escapeHtml(vj.status)}}</b> · 置信度 ${{escapeHtml(vj.confidence||'low')}}</p>${{(vj.reasons||[]).map(x=>`<p>• ${{escapeHtml(x)}}</p>`).join('')}}`;
const unverified=REPORT.verificationReport?.unverifiedItems||[];document.getElementById('risks').innerHTML=(unverified.length?unverified.map(x=>`<p>• ${{escapeHtml(typeof x==='string'?x:(x.item||x.reason||JSON.stringify(x)))}}</p>`).join(''):'<p class=PASS>无未验证项</p>');
const findings=[...(REPORT.findings||[]),...((REPORT.professionalFindings)||[])];document.getElementById('findingRows').innerHTML=findings.map(f=>`<tr><td class="${{f.severity}}">${{f.severity||''}}</td><td>${{escapeHtml(f.id||'')}}</td><td>${{escapeHtml(f.title||f.message||'')}}</td><td>${{escapeHtml(f.recommendation||f.evidence?.[0]?.excerpt||f.count||'')}}</td></tr>`).join('');
const journey=REPORT.browserComparisonReport?.journey||[];document.getElementById('journeyRows').innerHTML=journey.map(j=>`<tr><td class="${{j.status}}">${{j.status}}</td><td>${{escapeHtml(j.step||j.id||'')}}</td><td>${{j.durationMs??'-'}}</td><td>${{escapeHtml(j.reason||'')}}</td></tr>`).join('');
document.getElementById('engines').innerHTML=Object.entries(REPORT.professionalEngines||{{}}).map(([k,v])=>`<div class=card style="margin:8px 0"><b>${{escapeHtml(k)}}</b> <span class="${{v.status}}">${{v.status||'NOT_RUN'}}</span><pre>${{escapeHtml(JSON.stringify(v,null,2))}}</pre></div>`).join('')||'<p>没有专业引擎结果。</p>';
document.getElementById('raw').textContent=JSON.stringify(REPORT,null,2);const range=document.querySelector('.compare input');if(range)range.oninput=()=>document.querySelector('.compare .after').style.clipPath=`inset(0 ${{100-range.value}}% 0 0)`;
function escapeHtml(v){{return String(v??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]))}}const decisionEl=document.getElementById('decision'),reviewerEl=document.getElementById('reviewer'),commentEl=document.getElementById('comment');function load(){{const h=JSON.parse(localStorage.getItem(KEY)||'[]');document.getElementById('history').innerHTML=h.map(x=>`<div class=card style="margin:8px 0"><b>${{escapeHtml(x.decision)}}</b> · ${{escapeHtml(x.reviewer)}} · ${{escapeHtml(x.at)}}<p>${{escapeHtml(x.comment)}}</p></div>`).join('')}}function saveReview(){{const h=JSON.parse(localStorage.getItem(KEY)||'[]');h.unshift({{decision:decisionEl.value,reviewer:reviewerEl.value,comment:commentEl.value,at:new Date().toISOString(),reportDigest:REPORT.reportDigest||REPORT.planDigest}});localStorage.setItem(KEY,JSON.stringify(h));load()}}function exportReview(){{const blob=new Blob([JSON.stringify({{reportDigest:REPORT.reportDigest||REPORT.planDigest,history:JSON.parse(localStorage.getItem(KEY)||'[]')}},null,2)],{{type:'application/json'}});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='web-ui-quality-review.json';a.click();URL.revokeObjectURL(a.href)}}load();
</script></body></html>'''
    report_path = out / "index.html"
    report_path.write_text(page, encoding="utf-8")
    return report_path
