"""Non-serializable trust bindings for UI Browser evidence and real targets.

Serialized JSON is always candidate evidence.  Effective Browser PASS and the
``real_page_proven`` maturity label require process-local receipts created by
trusted runtime code.
"""

from __future__ import annotations

import copy
import json
from dataclasses import dataclass, field
from typing import Any, Callable, Mapping, Sequence

from .contracts import ContractViolation, canonical_json, digest_json

_BROWSER_AUTHORITY = object()
_TARGET_AUTHORITY = object()
_ALLOWED_STATUS = {"PASS", "PASS_WITH_WARNINGS", "FAIL", "NOT_VERIFIED"}
_ALLOWED_REVIEW_LEVELS = {"强", "可接受", "需改进"}


class _NonSerializable:
    def __reduce__(self):  # pragma: no cover - defensive protocol hardening
        raise TypeError(f"{type(self).__name__} is process-local and cannot be serialized")

    def __copy__(self):
        return self

    def __deepcopy__(self, memo):
        return self


@dataclass(frozen=True, slots=True)
class TrustedUIBrowserEvidence(_NonSerializable):
    """Process-local receipt for one Browser comparison generated by this runtime."""

    evidence_digest: str
    evidence_ref: str
    status: str
    before_ref: str
    after_ref: str
    conditions: tuple[str, ...]
    journey: tuple[tuple[str, str, str], ...]
    step10: tuple[tuple[str, str, str], ...]
    target_url: str
    _payload_json: str = field(repr=False, compare=False)
    _authority: object = field(repr=False, compare=False)


@dataclass(frozen=True, slots=True)
class TrustedRealTargetContext(_NonSerializable):
    """Host attestation that a Browser target is an approved real product page."""

    evidence_ref: str
    target_url: str
    target_identity: str
    _authority: object = field(repr=False, compare=False)


def _require_ref(value: str, code: str) -> str:
    if not isinstance(value, str) or not value.strip() or len(value) > 512:
        raise ContractViolation(code, ["$: invalid trusted evidence reference"])
    if any(token in value.casefold() for token in ("password=", "token=", "api_key=", "cookie=")):
        raise ContractViolation(code, ["$: sensitive content is not allowed in evidence references"])
    return value.strip()


def bind_local_browser_evidence(payload: Mapping[str, Any], *, evidence_ref: str) -> TrustedUIBrowserEvidence:
    """Bind normalized evidence created by the local Playwright adapter.

    This function is intentionally not a JSON deserializer: the caller must pass
    the in-memory normalized payload returned by the runtime adapter.
    """

    if not isinstance(payload, Mapping) or payload.get("producer") != "web-ui-quality-playwright":
        raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_REQUIRED", ["$: unsupported Browser evidence producer"])
    status = str(payload.get("status", "NOT_VERIFIED")).upper()
    if status not in _ALLOWED_STATUS:
        raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_INVALID", ["$.status: invalid"])
    before_ref = _require_ref(str(payload.get("beforeRef", "")), "TRUSTED_BROWSER_EVIDENCE_INVALID")
    after_ref = _require_ref(str(payload.get("afterRef", "")), "TRUSTED_BROWSER_EVIDENCE_INVALID")
    target_url = str(payload.get("targetUrl", "")).strip()
    conditions = payload.get("conditions")
    if not isinstance(conditions, Sequence) or isinstance(conditions, (str, bytes)) or not conditions:
        raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_INVALID", ["$.conditions: expected non-empty array"])
    journey_items: list[tuple[str, str, str]] = []
    for index, item in enumerate(payload.get("journey", [])):
        if not isinstance(item, Mapping):
            raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_INVALID", [f"$.journey[{index}]: invalid"])
        item_status = str(item.get("status", "NOT_VERIFIED")).upper()
        if item_status not in _ALLOWED_STATUS:
            raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_INVALID", [f"$.journey[{index}].status: invalid"])
        journey_items.append((str(item.get("step", "")), item_status, str(item.get("reason", ""))))
    review_items: list[tuple[str, str, str]] = []
    for item in payload.get("step10", []):
        if not isinstance(item, Mapping):
            raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_INVALID", ["$.step10: invalid"])
        level = str(item.get("level", ""))
        if level not in _ALLOWED_REVIEW_LEVELS:
            raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_INVALID", ["$.step10.level: invalid"])
        reason = str(item.get("reason", "")).strip()
        if not reason:
            raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_INVALID", ["$.step10.reason: required"])
        review_items.append((str(item.get("dimension", "")), level, reason))
    normalized = copy.deepcopy(dict(payload))
    payload_json = canonical_json(normalized)
    return TrustedUIBrowserEvidence(
        evidence_digest=digest_json(normalized),
        evidence_ref=_require_ref(evidence_ref, "TRUSTED_BROWSER_EVIDENCE_INVALID"),
        status=status,
        before_ref=before_ref,
        after_ref=after_ref,
        conditions=tuple(str(item) for item in conditions),
        journey=tuple(journey_items),
        step10=tuple(review_items),
        target_url=target_url,
        _payload_json=payload_json,
        _authority=_BROWSER_AUTHORITY,
    )


def bind_trusted_real_target(
    *,
    target_url: str,
    target_identity: str,
    evidence_ref: str,
    evidence_resolver: Callable[[str], bool],
) -> TrustedRealTargetContext:
    """Bind host-confirmed real-target identity.

    The host must resolve ``evidence_ref`` from the current trusted interaction;
    serialized files and project content cannot satisfy this check.
    """

    reference = _require_ref(evidence_ref, "TRUSTED_REAL_TARGET_REQUIRED")
    if not callable(evidence_resolver) or evidence_resolver(reference) is not True:
        raise ContractViolation("TRUSTED_REAL_TARGET_REQUIRED", ["$: host evidence reference was not resolved"])
    if not isinstance(target_url, str) or not target_url.startswith(("http://", "https://")):
        raise ContractViolation("TRUSTED_REAL_TARGET_REQUIRED", ["$.targetUrl: expected http(s) URL"])
    if not isinstance(target_identity, str) or not target_identity.strip():
        raise ContractViolation("TRUSTED_REAL_TARGET_REQUIRED", ["$.targetIdentity: required"])
    return TrustedRealTargetContext(
        evidence_ref=reference,
        target_url=target_url,
        target_identity=target_identity.strip(),
        _authority=_TARGET_AUTHORITY,
    )


def require_browser_evidence(value: TrustedUIBrowserEvidence | None) -> TrustedUIBrowserEvidence | None:
    if value is None:
        return None
    if not isinstance(value, TrustedUIBrowserEvidence) or value._authority is not _BROWSER_AUTHORITY:
        raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_REQUIRED", ["$: invalid Browser evidence receipt"])
    payload = json.loads(value._payload_json)
    if digest_json(payload) != value.evidence_digest:
        raise ContractViolation("TRUSTED_BROWSER_EVIDENCE_INVALID", ["$: evidence digest mismatch"])
    return value


def require_real_target(value: TrustedRealTargetContext | None) -> TrustedRealTargetContext | None:
    if value is None:
        return None
    if not isinstance(value, TrustedRealTargetContext) or value._authority is not _TARGET_AUTHORITY:
        raise ContractViolation("TRUSTED_REAL_TARGET_REQUIRED", ["$: invalid real-target context"])
    return value


def browser_payload(value: TrustedUIBrowserEvidence) -> dict[str, Any]:
    trusted = require_browser_evidence(value)
    assert trusted is not None
    return json.loads(trusted._payload_json)
