"""Keep runtime schemas as a mechanically generated copy of canonical ``schemas/``.

The public ``schemas/`` directory is the single source of truth. The runtime
copy is generated by ``scripts/sync_schema_bundle.py`` and release validation
checks full byte parity before packaging.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PUBLIC_DIR = ROOT / "schemas"
PACKAGED_DIR = ROOT / "runtime" / "python" / "web_ui_quality" / "schemas"

PUBLIC_SCHEMAS = sorted(path.name for path in PUBLIC_DIR.glob("*.json"))


def test_both_bundles_exist_and_are_non_empty():
    assert PUBLIC_SCHEMAS, "public schema bundle is empty"
    assert sorted(path.name for path in PACKAGED_DIR.glob("*.json")), "packaged schema bundle is empty"


def test_bundles_contain_the_same_file_names():
    public = set(PUBLIC_SCHEMAS)
    packaged = {path.name for path in PACKAGED_DIR.glob("*.json")}
    assert public == packaged, {
        "public_only": sorted(public - packaged),
        "packaged_only": sorted(packaged - public),
    }


@pytest.mark.parametrize("name", PUBLIC_SCHEMAS)
def test_schema_pair_is_semantically_identical(name):
    """Formatting may differ between the copies; the contract may not."""
    public = json.loads((PUBLIC_DIR / name).read_text(encoding="utf-8"))
    packaged = json.loads((PACKAGED_DIR / name).read_text(encoding="utf-8"))
    assert public == packaged, f"{name}: public and packaged schemas describe different contracts"


@pytest.mark.parametrize("name", PUBLIC_SCHEMAS)
def test_schema_is_valid_json_object_with_declared_version(name):
    packaged = json.loads((PACKAGED_DIR / name).read_text(encoding="utf-8"))
    assert isinstance(packaged, dict), f"{name}: schema root must be an object"
    assert packaged.get("$schema") or packaged.get("type") or packaged.get("properties"), (
        f"{name}: schema has no $schema, type, or properties key"
    )



def test_schema_sync_helper_check_passes() -> None:
    import subprocess
    import sys

    completed = subprocess.run(
        [sys.executable, "-B", "scripts/sync_schema_bundle.py", "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=30,
    )
    assert completed.returncode == 0, (completed.stdout, completed.stderr)
    payload = json.loads(completed.stdout)
    assert payload["status"] == "PASS"
    assert payload["mode"] == "CHECK"
    assert payload["schemas"] == len(PUBLIC_SCHEMAS)
