const DATA=[
 {id:'northstar',name:'Northstar Logistics',owner:'Maya Chen',status:'active',value:'$84,000',stage:'Negotiation',activity:'2 hours ago',risk:false},
 {id:'fieldnote',name:'Fieldnote Labs',owner:'Leo Allen',status:'risk',value:'$42,500',stage:'Evaluation',activity:'Yesterday',risk:true},
 {id:'harbor',name:'Harbor Finance',owner:'Ari Singh',status:'active',value:'$126,000',stage:'Proposal',activity:'3 days ago',risk:false},
 {id:'acorn',name:'Acorn Health',owner:'Maya Chen',status:'active',value:'$67,800',stage:'Discovery',activity:'5 days ago',risk:false}
];
const $=id=>document.getElementById(id);const requestedState=new URLSearchParams(location.search).get('state');const state=['risk-filter','empty-search','selected-risk'].includes(requestedState)?requestedState:'initial';document.body.dataset.wuqState=state;let filter=state==='risk-filter'?'risk':'all',selected=state==='empty-search'?null:['risk-filter','selected-risk'].includes(state)?'fieldnote':DATA[0].id;
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function visible(){const q=$('search').value.trim().toLowerCase();return DATA.filter(x=>(filter==='all'||x.status===filter)&&(!q||`${x.name} ${x.owner}`.toLowerCase().includes(q)))}
function renderList(){const items=visible();$('resultCount').textContent=`${items.length} account${items.length===1?'':'s'}`;$('accounts').innerHTML=items.map(x=>`<button class="account" role="option" aria-selected="${x.id===selected}" data-id="${x.id}"><span class="avatar">${esc(x.name.slice(0,1))}</span><span><b>${esc(x.name)}</b><span>${esc(x.owner)} · ${esc(x.stage)}</span></span><small class="${x.risk?'risk':''}">${x.risk?'Needs attention':esc(x.activity)}</small></button>`).join('');$('empty').hidden=items.length>0;$('accounts').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.id;renderList();renderDetail();if(innerWidth<521)$('detail').classList.add('mobile-open')})}
function renderDetail(){const x=DATA.find(item=>item.id===selected);if(!x){$('detail').innerHTML='<div class="detail-empty"><span class="tag">NO SELECTION</span><h2>No account selected</h2><p>Choose an account from the list to review its details.</p></div>';return}$('detail').innerHTML=`<div class="detail-top"><div><span class="tag">${x.risk?'AT RISK':'ACTIVE'}</span><h2 data-wuq-detail-title>${esc(x.name)}</h2><span>${esc(x.owner)} · ${esc(x.stage)}</span></div><button aria-label="Close details" id="close">×</button></div><div class="facts"><div class="fact"><span>Pipeline value</span><b>${esc(x.value)}</b></div><div class="fact"><span>Last activity</span><b>${esc(x.activity)}</b></div><div class="fact"><span>Next step</span><b>Confirm implementation review</b></div><div class="fact"><span>Health</span><b>${x.risk?'Follow-up overdue':'On track'}</b></div></div><section class="timeline"><h3>Recent activity</h3><div class="event"><i></i><div><p>Shared product requirements and timeline</p><small>Meeting · ${esc(x.owner)}</small></div></div><div class="event"><i></i><div><p>Updated opportunity stage to ${esc(x.stage)}</p><small>System event</small></div></div></section><div class="actions"><button id="note">Add note</button><button class="primary" id="next">Record next action</button></div>`;$('close').onclick=()=>$('detail').classList.remove('mobile-open');$('note').onclick=()=>toast('Note draft opened');$('next').onclick=()=>toast('Next action saved locally for demo')}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
$('search').oninput=renderList;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));renderList()});$('clear').onclick=()=>{$('search').value='';filter='all';document.body.dataset.wuqState='initial';document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x.dataset.filter==='all'));renderList()};$('newAccount').onclick=()=>toast('New account flow is disabled in this demo');$('sort').onclick=()=>toast('Sorted by last activity');if(state==='empty-search')$('search').value='no-match-for-baseline';renderList();renderDetail();
